name: Test runner

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, windows-2019, macos-10.15]
        jdk: [8, 9, 10, 11, 12, 13, 14]

    name: Test on ${{ matrix.os }} with JDK${{ matrix.jdk }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - run: lein test-all
